kind = "web"
previewPath = "/"
title = "Czy pójdziesz ze mną na randkę?"
version = "1.0.0"
id = "artifacts/randka"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26259

[services.development]
run = "pnpm --filter @workspace/randka run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/randka", "run", "build" ]
publicDir = "artifacts/randka/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26259"
BASE_PATH = "/"
